## 1.파이썬 리스트[] 에 데이터를 담아서 만들기

In [1]:
import pandas as pd
data_list = [[1,'kim',111],[2,'lee',222]]
col_list=['seq','id','pw']
# data=None,
# index: Axes | None = None,
# columns: Axes | None = None,
# dtype: Dtype | None = None,
# copy: bool | None = None,
df = pd.DataFrame(data = data_list,
                  columns = col_list
                  )

print(df.info())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   seq     2 non-null      int64 
 1   id      2 non-null      object
 2   pw      2 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 176.0+ bytes
None


In [2]:
df.head() #5개만 보여줘

seq   id   pw
0    1  kim  111
1    2  lee  222

## 2.배열로 데이터를 담아서 만들기

In [3]:
import pandas as pd   #pandas.py
import numpy as np    #numpy.py
data_list = [[1,'kim',111],[2,'lee',222]]
data_arr = np.array(data_list)
col_list=['seq','id','pw']
# data=None,
# index: Axes | None = None,
# columns: Axes | None = None,
# dtype: Dtype | None = None,
# copy: bool | None = None,
df = pd.DataFrame(data = data_arr,
                  columns = col_list
                  )

print(df.info())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   seq     2 non-null      object
 1   id      2 non-null      object
 2   pw      2 non-null      object
dtypes: object(3)
memory usage: 176.0+ bytes
None


In [4]:
df.head()

seq   id   pw
0   1  kim  111
1   2  lee  222

## 3. 파일(csv,txt,eccel,html...)데이터를 불러서 만들기

In [4]:
df = pd.read_csv('./book/data/total_sales_data.csv') #sep=','



In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   매장명     9 non-null      object
 1   제품종류    9 non-null      object
 2   모델명     9 non-null      object
 3   판매      9 non-null      int64 
 4   재고      9 non-null      int64 
dtypes: int64(2), object(3)
memory usage: 488.0+ bytes


In [6]:
df.head() # 기본5개

매장명  제품종류 모델명  판매  재고
0   A  스마트폰  S1   1   2
1   A  스마트폰  S2   2   5
2   A    TV  V1   3   5
3   B  스마트폰  S2   4   6
4   B  스마트폰  S1   5   8

In [16]:
df ####주소쫒아가세요 하지마세요,,,

매장명  제품종류 모델명  판매  재고
0   A  스마트폰  S1   1   2
1   A  스마트폰  S2   2   5
2   A    TV  V1   3   5
3   B  스마트폰  S2   4   6
4   B  스마트폰  S1   5   8
5   B    TV  V1   6   9
6   C  스마트폰  S2   2   4
7   C    TV  V1   3   6
8   C    TV  V2   7   9

In [7]:
df.tail() #끝에서부터 5개

매장명  제품종류 모델명  판매  재고
4   B  스마트폰  S1   5   8
5   B    TV  V1   6   9
6   C  스마트폰  S2   2   4
7   C    TV  V1   3   6
8   C    TV  V2   7   9

In [9]:
df.iloc[[3,4],[1,2]]

제품종류 모델명
3  스마트폰  S2
4  스마트폰  S1

In [8]:
df.iloc[[3,4],2:3]

모델명
3  S2
4  S1

In [36]:
df.head()

매장명  제품종류 모델명  판매  재고
0   A  스마트폰  S1   1   2
1   A  스마트폰  S2   2   5
2   A    TV  V1   3   5
3   B  스마트폰  S2   4   6
4   B  스마트폰  S1   5   8

In [13]:
df[  df['재고'] == 6]   #복잡해도 이문법을 추천합니다.

매장명  제품종류 모델명  판매  재고
3   B  스마트폰  S2   4   6
7   C    TV  V1   3   6

In [30]:
df[ ['재고','판매'] ].head()  #추천

재고  판매
0   2   1
1   5   2
2   5   3
3   6   4
4   8   5

In [31]:
df[ ['재고','판매'] ]

재고  판매
0   2   1
1   5   2
2   5   3
3   6   4
4   8   5
5   9   6
6   4   2
7   6   3
8   9   7

In [29]:
df.iloc[:,[3,4]]

판매  재고
0   1   2
1   2   5
2   3   5
3   4   6
4   5   8
5   6   9
6   2   4
7   3   6
8   7   9

In [28]:
df.재고

0    2
1    5
2    5
3    6
4    8
5    9
6    4
7    6
8    9
Name: 재고, dtype: int64

In [12]:
df[  df.재고 == 6]

매장명  제품종류 모델명  판매  재고
3   B  스마트폰  S2   4   6
7   C    TV  V1   3   6

## 파이썬 딕트에 담아서 데이터 활용하기

In [4]:
list = [{'국어':100,'영어':95,'수학':90},{'국어':99,'영어':92,'수학':80},{'국어':90,'영어':85,'수학':98}]

df = pd.DataFrame(list)     # 프레임으로 만들면 국어,영어,수학이 컬럼으로 간다
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   국어      3 non-null      int64
 1   영어      3 non-null      int64
 2   수학      3 non-null      int64
dtypes: int64(3)
memory usage: 200.0 bytes


국어  영어  수학
0  100  95  90
1   99  92  80
2   90  85  98

In [37]:
s = pd.Series({'국어':100,'영어':95,'수학':90})
s

국어    100
영어     95
수학     90
dtype: int64

In [47]:
dict_data = {'국어': [100, 50,20],
              '영어': [90,55,22],
              '수학': [80,57,27]}
df = pd.DataFrame(dict_data) 
df.head()

국어  영어  수학
0  100  90  80
1   50  55  57
2   20  22  27

In [50]:
dict_data = {'국어': [100, 50,20],
              '영어': [90,55,22],
              '수학': [80,57,27]}
df = pd.DataFrame(dict_data)
df.columns=['kor','eng','math']
df.head()

kor  eng  math
0  100   90    80
1   50   55    57
2   20   22    27

In [55]:
print(s.index,
s.values,
df.index,
df.values,
df.columns)

Index(['국어', '영어', '수학'], dtype='object') [100  95  90] RangeIndex(start=0, stop=3, step=1) [[100  90  80]
 [ 50  55  57]
 [ 20  22  27]] Index(['kor', 'eng', 'math'], dtype='object')


In [5]:
df = pd.read_csv("./lec12_sample.txt", sep = '\t')
df.index = ['A0','A1','A2','A3','A4']

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   col0    5 non-null      int64 
 1   col1    5 non-null      object
 2   col2    5 non-null      int64 
 3   col3    5 non-null      int64 
dtypes: int64(3), object(1)
memory usage: 288.0+ bytes


In [120]:
df.head()

col0   col1  col2  col3
A0     0  name0     0     0
A1     1  name1    10  1000
A2     2  name2    20  2000
A3     3  name3    30  3000
A4     4  name4    40  4000

In [6]:
arr = np.array([ [1,11,111,1111],[2,22,222,2222],[3,33,333,3333],[4,44,444,4444],[5,55,555,5555] ])
print(arr)

[[   1   11  111 1111]
 [   2   22  222 2222]
 [   3   33  333 3333]
 [   4   44  444 4444]
 [   5   55  555 5555]]


In [7]:
df.shape , arr.shape

((5, 4), (5, 4))

* 줄만 핸들링

In [8]:
arr[0]

array([   1,   11,  111, 1111])

In [82]:
# df[0]      # 이런 문법은 없다. 에러

In [10]:
arr[0:3]    #0,1,2번째 줄가져온다

array([[   1,   11,  111, 1111],
       [   2,   22,  222, 2222],
       [   3,   33,  333, 3333]])

In [11]:
df[0:3]     #0,1,2번째 줄가져온다

col0   col1  col2  col3
A0     0  name0     0     0
A1     1  name1    10  1000
A2     2  name2    20  2000

In [12]:
arr[[0,1,2]]

array([[   1,   11,  111, 1111],
       [   2,   22,  222, 2222],
       [   3,   33,  333, 3333]])

In [81]:
#df[[0,1,2]]     #에러

In [80]:
# df[] 에서 줄로 표현하는 값을 넣는 행위는 에러가 난다.

In [86]:
# 줄핸들링
# ~번째 arr[2], df[2]   df에러난다.
# ~번째가 여러개일 경우 arr[[1,2]], df[[1,2]] 에러난다.
# 슬라이싱 arr[:], df[:] 는 가능하다.

In [88]:
# ---------------------------------------------------------------------------------------------------------------------------

In [13]:
arr[0,1]

11

In [91]:
# df[0,1] 에러난다    df[줄,칸] x

In [93]:
# df[ 0:2 , 1 ]  에러 df[ㄱ:ㄷ, 칸] x

In [95]:
#     df [a:e] 슬라이싱 표현은 df에서는 줄로만 찾아준다.

In [98]:
# df['0':'3'] # 에러납니다. 값으로 슬라이싱 안돼요.

In [99]:
# df[a:s,e:g] ### 에러

In [14]:
df['col1']

A0    name0
A1    name1
A2    name2
A3    name3
A4    name4
Name: col1, dtype: object

In [15]:
df[  ['col1','col2']  ]  #------------------------------------->99% 쓰는 문법

col1  col2
A0  name0     0
A1  name1    10
A2  name2    20
A3  name3    30
A4  name4    40

In [104]:
# df['col':'col2'] ----> error df 구조 안에서 슬라이싱 안됃아노돼

* iloc, loc

In [16]:
print(arr[0,0])
print(arr[0:2,0:2])
print(arr[[0,1,2],[1,2,3]])

1
[[ 1 11]
 [ 2 22]]
[  11  222 3333]


In [17]:
df.iloc[0:2]  #0,1번째   #----------------인덱스로 접근할때 쓰는 아이락. 99% 많이씀

df.iloc[[0,1,2]]

col0   col1  col2  col3
A0     0  name0     0     0
A1     1  name1    10  1000
A2     2  name2    20  2000

In [130]:
df.iloc[0]    #-----Series 시리즈라서 출력방식이 다르게 나온다!

col0        0
col1    name0
col2        0
col3        0
Name: A0, dtype: object

In [124]:
# df[0:2]   ----- 되는데 아이락 그냥 붙여라

In [18]:
df.loc['A0']
df.loc['A0':'A2']

col0   col1  col2  col3
A0     0  name0     0     0
A1     1  name1    10  1000
A2     2  name2    20  2000

In [19]:
df.loc[['A0','A1','A2']]

col0   col1  col2  col3
A0     0  name0     0     0
A1     1  name1    10  1000
A2     2  name2    20  2000

* 1줄 기준 칸,(컬럼)제어

In [20]:
df.iloc[1,1]

'name1'

In [21]:
df.iloc[1,1:3]

col1    name1
col2       10
Name: A1, dtype: object

In [22]:
df.iloc[1,[1,2]]

col1    name1
col2       10
Name: A1, dtype: object

In [23]:
df.iloc[1:3, 1:3]

col1  col2
A1  name1    10
A2  name2    20

In [25]:
df.iloc[[1,2,3],[1,2]]

col1  col2
A1  name1    10
A2  name2    20
A3  name3    30

In [26]:
df.loc['A1']

col0        1
col1    name1
col2       10
col3     1000
Name: A1, dtype: object

In [27]:
df.loc['A1','col2']

10

In [28]:
df.loc['A1':'A3', 'col1':'col2']

col1  col2
A1  name1    10
A2  name2    20
A3  name3    30

In [29]:
df.loc['A1',['col0','col2']]

col0     1
col2    10
Name: A1, dtype: object

In [31]:
df.loc[['A1','A3'],'col0':'col3']

col0   col1  col2  col3
A1     1  name1    10  1000
A3     3  name3    30  3000

In [1]:
#  loc 은 iloc의 개념과는 다르게 인덱스처럼 -1해서 가져오는게 아니라 값으로 가져오는거라 지정된 값 까지 가져와야한다

In [32]:
df[0:2][0:1]    ### 허허....

col0   col1  col2  col3
A0     0  name0     0     0

In [161]:
# 락과 아이락만 잘쓰자 어렵게 생각하지마라.